/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_verify_VerifyTest */

#ifndef _Included_com_example_verify_VerifyTest
#define _Included_com_example_verify_VerifyTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_verify_VerifyTest
 * Method:    getRandValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_verify_VerifyTest_getRandValue
  (JNIEnv *, jobject);

/*
 * Class:     com_example_verify_VerifyTest
 * Method:    getStringValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_verify_VerifyTest_getStringValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
