/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_verify_VerifyClass */

#ifndef _Included_com_example_verify_VerifyClass
#define _Included_com_example_verify_VerifyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_verify_VerifyClass
 * Method:    createObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_verify_VerifyClass_createObject
  (JNIEnv *, jobject);

/*
 * Class:     com_example_verify_VerifyClass
 * Method:    setValue
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_verify_VerifyClass_setValue
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_example_verify_VerifyClass
 * Method:    getValue
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_verify_VerifyClass_getValue
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif