/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_verify_VerifyCallback */

#ifndef _Included_com_example_verify_VerifyCallback
#define _Included_com_example_verify_VerifyCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_verify_VerifyCallback
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_verify_VerifyCallback_start
  (JNIEnv *, jobject);

/*
 * Class:     com_example_verify_VerifyCallback
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_verify_VerifyCallback_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_verify_VerifyCallback
 * Method:    startListenTransmitter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_verify_VerifyCallback_startListenTransmitter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
